name: Create Terraform Remote State

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  GH_PAT_TOKEN: ${{ secrets.GH_PAT_TOKEN }}
  
jobs:
  build:
    name: Create S3 Bucket
    runs-on: ubuntu-latest
    
    steps:
      - name: Create ENV variable
        run: |
          echo "${{ AWS_DEFAULT_REGION }}"
          
