name: Create Terraform Remote State

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  GH_PAT_TOKEN: ${{ secrets.GH_PAT_TOKEN }}
  
jobs:
  job1:
    name: Create S3 Bucket
    runs-on: ubuntu-latest
    outputs:
      BUCKET_NAME: ${{steps.bucket.outputs.BUCKET_NAME}}
    
    steps: 
      - name: Generate Bucket Name
        id: "bucket"
        run: |
          echo "BUCKET_NAME="tf-rm-st-bkt-$(echo $RANDOM | md5sum | head -c 7)"" >> $GITHUB_OUTPUT
      - name: Create Bucket
        run: |
          aws s3api create-bucket --bucket "${{steps.bucket.outputs.BUCKET_NAME}}" --region "${{ env.AWS_DEFAULT_REGION }}"
      - name: Put Bucket Versioning
        run: |
          aws s3api put-bucket-versioning --bucket "${{steps.bucket.outputs.BUCKET_NAME}}" --versioning-configuration Status=Enabled
      - name: Put Bucket Encryption
        run: |
          aws s3api put-bucket-encryption --bucket "${{steps.bucket.outputs.BUCKET_NAME}}" --server-side-encryption-configuration '{"Rules": [{"ApplyServerSideEncryptionByDefault": {"SSEAlgorithm": "AES256"}}]}'
      
  job2:
    name: Create Dynamodb Table
    runs-on: ubuntu-latest
    outputs:
      TABLE_NAME: ${{steps.table.outputs.TABLE_NAME}}
    needs: job1
    
    steps:
      - name: Generate Table Name
        id: table
        run: |
          echo "TABLE_NAME=$(echo "${{needs.bucket.outputs.BUCKET_NAME}}" | sed 's/bkt/tbl/g')" >> $GITHUB_OUTPUT
      - name: Create Table
        run: |
          aws dynamodb create-table --table-name "${{steps.table.outputs.TABLE_NAME}}" --attribute-definitions AttributeName=LockID,AttributeType=S --key-schema AttributeName=LockID,KeyType=HASH --billing-mode PAY_PER_REQUEST