name: Create Terraform Remote State

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  GH_PAT_TOKEN: ${{ secrets.GH_PAT_TOKEN }}
  
jobs:
  job1:
    name: Create S3 Bucket
    runs-on: ubuntu-latest
    
    outputs:
      bucket: ${{ steps.bkt_name.outputs.bucket }}
    
    steps: 
      - name: Generate Bucket Name
        id: bkt_name
        run: |
          echo "BUCKET_NAME="tf-rm-st-bkt-$(echo $RANDOM | md5sum | head -c 7)"" >> $GITHUB_ENV
      - name: Create Bucket
        run: |
          aws s3api create-bucket --bucket $BUCKET_NAME --region "${{ env.AWS_DEFAULT_REGION }}"
      - name: Put Bucket Versioning
        run: |
          aws s3api put-bucket-versioning --bucket $BUCKET_NAME --versioning-configuration Status=Enabled
      - name: Put Bucket Encryption
        run: |
          aws s3api put-bucket-encryption --bucket $BUCKET_NAME --server-side-encryption-configuration '{"Rules": [{"ApplyServerSideEncryptionByDefault": {"SSEAlgorithm": "AES256"}}]}'
      
  job2:
    name: Create Dynamodb Table
    runs-on: ubuntu-latest
    needs: job1
    
    steps:
      - name: Generate Table Name
        run: |
          echo "TABLE_NAME=$(aws s3api list-buckets --query "Buckets[].Name" --output text | grep -o "tf-rm-st-bkt-[a-zA-Z0-9]*" | head -n1 | sed 's/bkt/tbl/g')" >> $GITHUB_ENV
      - name: Create Table
        run: |
          echo "$TABLE_NAME"