name: Delete Terraform Remote State

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  GH_PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

jobs:
  job1:
    name: Delete S3 Buckets
    runs-on: ubuntu-latest
    
    steps: 
      - name: Query a List of Tables Names
        run: |
          echo "aws dynamodb list-tables --output text | grep "TABLENAMES" | awk "{print $2}"" 

