name: Delete Terraform Remote State

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  GH_PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

jobs:
  job1:
    name: Delete S3 Buckets
    runs-on: ubuntu-latest
    
    steps: 
      - name: Query a List of Bucket Names
        run: |
          echo "BUCKETS=( $(aws s3api list-buckets --query "Buckets[].Name" --output text) )" >> $GITHUB_ENV
      - name: Read List of Buckets
        run: |
          echo "${BUCKETS[@]}"
          echo "for BUCKET in ${BUCKETS[@]}; do echo "$BUCKET"; done"